apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  annotations:
  {{- if and .Values.vcsInfo.repoUrl .Values.vcsInfo.branch }}
    app.openshift.io/vcs-ref: {{ .Values.vcsInfo.branch }}
    app.openshift.io/vcs-uri: {{ .Values.vcsInfo.repoUrl }}
  {{- end }}
  {{- if .Values.connectsTo }}
    app.openshift.io/connects-to: {{ .Values.connectsTo }}
  {{- end }}
  labels:
    app: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      {{- if .Values.image.secretName }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{- end }}
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          env:
            - name: INGRESS_HOST
              value: ""
            - name: PROTOCOLS
              value: ""
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
          envFrom:
            - secretRef:
                name: bank-db-secret
            - secretRef:
                name: bank-oidc-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
